(()=>{"use strict";
const USER_KEY="sspos_users_v2",LEGACY_USER_KEY="sspos_users_v1",CURRENT_KEY="sspos_current_user_v1",TX_KEY="sspos_transactions_v1",PRODUCT_KEY="sspos_products_v2",SNAPSHOT_KEY="sspos_owner_snapshot_v1";
const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])),money=n=>`$${Number(n||0).toFixed(2)}`,uid=()=>crypto?.randomUUID?crypto.randomUUID():`user-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const ALL_PERMS=["sale","inventory","purchase-orders","receiving","vendors","transactions","returns","customers","reports","users","manager","settings"];
const LABELS={sale:"New Sale",inventory:"Inventory","purchase-orders":"Purchase Orders",receiving:"Receiving",vendors:"Vendors",transactions:"Transactions",returns:"Returns",customers:"Customers",reports:"Reports",users:"Users",manager:"Manager",settings:"Settings"};
const PRESETS={Employee:["sale","transactions","returns","customers"],Manager:["sale","inventory","purchase-orders","receiving","vendors","transactions","returns","customers","reports","manager"],Owner:[...ALL_PERMS]};
function defaultOwner(){return{id:"owner",name:"Owner",role:"Owner",pin:"",email:"",phone:"",active:true,permissions:[...ALL_PERMS]}}
function loadUsers(){try{const r=localStorage.getItem(USER_KEY);if(r){const u=JSON.parse(r);if(Array.isArray(u)&&u.length)return u}}catch{}let legacy=[];try{legacy=JSON.parse(localStorage.getItem(LEGACY_USER_KEY)||"[]")}catch{}const users=(legacy.length?legacy:[defaultOwner()]).map(u=>({...u,permissions:Array.isArray(u.permissions)?u.permissions:[...(PRESETS[u.role]||PRESETS.Employee)]}));if(!users.some(u=>u.role==="Owner"))users.unshift(defaultOwner());localStorage.setItem(USER_KEY,JSON.stringify(users));return users}
function saveUsers(u){localStorage.setItem(USER_KEY,JSON.stringify(u))}
function loadTx(){try{return JSON.parse(localStorage.getItem(TX_KEY)||"[]")}catch{return[]}}
function loadProducts(){try{return JSON.parse(localStorage.getItem(PRODUCT_KEY)||"[]")}catch{return[]}}
function currentUser(){const users=loadUsers();let id=localStorage.getItem(CURRENT_KEY)||"owner";let u=users.find(x=>String(x.id)===String(id)&&x.active!==false);if(!u){u=users.find(x=>x.active!==false&&x.role==="Owner")||users.find(x=>x.active!==false)||defaultOwner();localStorage.setItem(CURRENT_KEY,u.id)}return u}
function setCurrentUser(u){localStorage.setItem(CURRENT_KEY,u.id);applyPermissions();updateUserCard();toast(`Signed in as ${u.name}.`)}
function can(view){const u=currentUser();return u.role==="Owner"||((u.permissions||PRESETS[u.role]||[]).includes(view))}
function show(){$('saleView')?.classList.add('hidden');$('inventoryView')?.classList.add('hidden');$('placeholderView')?.classList.remove('hidden')}
function active(v){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===v))}
function toast(m){const t=$('toast');if(!t)return;t.textContent=m;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),2300)}
function modal(title,body){const c=$('modalCard'),b=$('modalBackdrop');if(!c||!b)return;c.innerHTML=`<div class="modal-head"><h3>${esc(title)}</h3><button class="modal-close" data-ur-close type="button">×</button></div>${body}`;b.classList.remove('hidden');setTimeout(()=>c.querySelector('input,select,button:not([data-ur-close])')?.focus(),0)}
function close(){$('modalBackdrop')?.classList.add('hidden');if($('modalCard'))$('modalCard').innerHTML=''}
function updateUserCard(){const u=currentUser(),card=document.querySelector('.user-card');if(!card)return;card.style.cursor='pointer';card.title='Switch employee';const av=card.querySelector('.avatar'),name=card.querySelector('strong'),role=card.querySelector('span');if(av)av.textContent=(u.name||'U').trim().charAt(0).toUpperCase();if(name)name.textContent=u.name;if(role)role.textContent=u.role}
function applyPermissions(){const u=currentUser();document.querySelectorAll('.nav-btn[data-view]').forEach(b=>{const v=b.dataset.view;b.style.display=(u.role==="Owner"||(u.permissions||[]).includes(v))?'':'none'});updateUserCard()}
function switchUserModal(){const users=loadUsers().filter(u=>u.active!==false);modal('Switch Employee',`<div class="ur-switch-list">${users.map(u=>`<button type="button" class="ur-switch-user" data-switch-user="${esc(u.id)}"><span class="ur-avatar">${esc((u.name||'U').charAt(0).toUpperCase())}</span><span><strong>${esc(u.name)}</strong><small>${esc(u.role)}</small></span></button>`).join('')}</div>`)}
function trySwitch(id){const u=loadUsers().find(x=>String(x.id)===String(id)&&x.active!==false);if(!u)return;if(u.pin){modal(`Sign in — ${u.name}`,`<form id="urPinForm"><div class="field"><label>Employee PIN</label><input id="urSwitchPin" type="password" inputmode="numeric" maxlength="6" autocomplete="off"></div><div id="urPinError" class="ur-error"></div><div class="modal-actions"><button class="secondary-btn" type="button" data-ur-close>Cancel</button><button class="primary-btn" type="submit">Sign In</button></div></form>`);$('urPinForm').addEventListener('submit',e=>{e.preventDefault();if($('urSwitchPin').value!==u.pin){$('urPinError').textContent='Incorrect PIN.';return}close();setCurrentUser(u)})}else{close();setCurrentUser(u)}}
function permissionGrid(perms){return `<div class="ur-permissions">${ALL_PERMS.map(p=>`<label><input type="checkbox" data-perm="${p}" ${perms.includes(p)?'checked':''}><span>${esc(LABELS[p])}</span></label>`).join('')}</div>`}
function renderUsers(){if(!can('users')){toast('You do not have permission to manage users.');return}show();active('users');const u=loadUsers();$('placeholderView').innerHTML=`<div class="ur-page"><div class="ur-head"><div><h1>Users</h1><p>Employees, roles, PINs, permissions and access status.</p></div><button id="urAddUser" class="primary-btn" type="button">+ Add Employee</button></div><div class="ur-role-note"><strong>Role defaults:</strong> Employee = sales/customers/transactions/returns · Manager = operations + reports · Owner = full access. Permissions can be customized per employee.</div><div class="ur-table-wrap"><table class="ur-table"><thead><tr><th>Name</th><th>Role</th><th>PIN</th><th>Email</th><th>Phone</th><th>Status</th><th></th></tr></thead><tbody>${u.map(x=>`<tr data-user-id="${esc(x.id)}"><td><strong>${esc(x.name)}</strong>${String(x.id)===String(currentUser().id)?'<small class="ur-current">Current</small>':''}</td><td>${esc(x.role)}</td><td>${x.pin?'••••':'—'}</td><td>${esc(x.email||'—')}</td><td>${esc(x.phone||'—')}</td><td><span class="${x.active?'ur-active':'ur-inactive'}">${x.active?'Active':'Inactive'}</span></td><td><button class="secondary-btn ur-edit" type="button">Edit</button></td></tr>`).join('')}</tbody></table></div></div>`}
function userForm(user){const edit=!!user,role=user?.role||'Employee',perms=Array.isArray(user?.permissions)?user.permissions:[...(PRESETS[role]||PRESETS.Employee)];modal(edit?'Edit Employee':'Add Employee',`<form id="urUserForm"><div class="form-grid"><div class="field full"><label>Name *</label><input id="urName" required value="${esc(user?.name||'')}"></div><div class="field"><label>Role *</label><select id="urRole"><option ${role==='Employee'?'selected':''}>Employee</option><option ${role==='Manager'?'selected':''}>Manager</option><option ${role==='Owner'?'selected':''}>Owner</option></select></div><div class="field"><label>PIN</label><input id="urPin" inputmode="numeric" maxlength="6" placeholder="4–6 digits" value="${esc(user?.pin||'')}"></div><div class="field"><label>Email</label><input id="urEmail" type="email" value="${esc(user?.email||'')}"></div><div class="field"><label>Phone</label><input id="urPhone" value="${esc(user?.phone||'')}"></div><div class="field full"><label>Permissions</label>${permissionGrid(perms)}</div><div class="field full"><label class="check-row"><input id="urActive" type="checkbox" ${user?.active===false?'':'checked'}><span>Active user</span></label></div></div><div class="modal-actions">${edit&&user?.role!=="Owner"?'<button id="urDeleteUser" class="danger-btn" type="button">Delete Employee</button>':''}<button class="secondary-btn" data-ur-close type="button">Cancel</button><button class="primary-btn" type="submit">${edit?'Save Changes':'Create Employee'}</button></div></form>`);
const roleEl=$('urRole');roleEl.addEventListener('change',()=>{const preset=PRESETS[roleEl.value]||[];document.querySelectorAll('[data-perm]').forEach(cb=>cb.checked=preset.includes(cb.dataset.perm))});
$('urUserForm').addEventListener('submit',e=>{e.preventDefault();const users=loadUsers(),pin=$('urPin').value.trim();if(pin&&!/^\d{4,6}$/.test(pin)){toast('PIN must be 4 to 6 digits.');return}const selected=[...document.querySelectorAll('[data-perm]:checked')].map(x=>x.dataset.perm),d={name:$('urName').value.trim(),role:$('urRole').value,pin,email:$('urEmail').value.trim(),phone:$('urPhone').value.trim(),active:$('urActive').checked,permissions:selected};if(!d.name)return;if(d.role==='Owner')d.permissions=[...ALL_PERMS];if(edit){const target=users.find(x=>String(x.id)===String(user.id));Object.assign(target,d)}else users.push({id:uid(),...d});saveUsers(users);close();applyPermissions();renderUsers();toast(edit?'Employee updated.':'Employee added.')});
$('urDeleteUser')?.addEventListener('click',()=>{if(!confirm(`Delete ${user.name}?`))return;const users=loadUsers().filter(x=>String(x.id)!==String(user.id));saveUsers(users);if(String(currentUser().id)===String(user.id))localStorage.setItem(CURRENT_KEY,'owner');close();applyPermissions();renderUsers();toast('Employee deleted.')})}
function rangeStart(r){const n=new Date();n.setHours(0,0,0,0);if(r==='today')return n;if(r==='7'){n.setDate(n.getDate()-6);return n}if(r==='30'){n.setDate(n.getDate()-29);return n}if(r==='90'){n.setDate(n.getDate()-89);return n}return new Date(0)}
function filteredTx(r){return loadTx().filter(t=>new Date(t.createdAt)>=rangeStart(r))}
function isCompleted(t){return (t.status||'Completed')==='Completed'&&Number(t.total||0)>=0}
function isReturn(t){return ['Returned','Refunded','Return'].includes(t.status)||Number(t.total||0)<0}
function payTotals(t){let cash=0,card=0;(t.payments||[]).forEach(p=>{if(p.type==='Cash')cash+=Number(p.amount||0);if(p.type==='Card')card+=Number(p.amount||0)});return{cash,card}}
function productLookup(){const m=new Map();loadProducts().forEach(p=>m.set(String(p.name||'').toLowerCase(),p));return m}
function reportData(r){const all=filteredTx(r),tx=all.filter(isCompleted),returns=all.filter(isReturn),sales=tx.reduce((s,t)=>s+Number(t.total||0),0),disc=tx.reduce((s,t)=>s+Number(t.discountAmount||0),0),ret=returns.reduce((s,t)=>s+Math.abs(Number(t.total||0)),0),pay=tx.reduce((a,t)=>{const p=payTotals(t);a.cash+=p.cash;a.card+=p.card;return a},{cash:0,card:0}),products=productLookup(),prod=new Map(),cat=new Map(),emp=new Map();let cogs=0;
tx.forEach(t=>{const e=emp.get(t.employee||'Owner')||{transactions:0,sales:0};e.transactions++;e.sales+=Number(t.total||0);emp.set(t.employee||'Owner',e);(t.items||[]).forEach(i=>{const qty=Number(i.qty||0),line=Number(i.lineTotal||0),p=products.get(String(i.name||'').toLowerCase()),cost=Number(p?.cost||0)*qty,category=p?.category||'Uncategorized';cogs+=cost;const pv=prod.get(i.name||'Item')||{qty:0,sales:0,cost:0,category};pv.qty+=qty;pv.sales+=line;pv.cost+=cost;prod.set(i.name||'Item',pv);const cv=cat.get(category)||{qty:0,sales:0,cost:0};cv.qty+=qty;cv.sales+=line;cv.cost+=cost;cat.set(category,cv)})});return{all,tx,returns,sales,disc,ret,pay,cogs,gross:sales-cogs,avg:tx.length?sales/tx.length:0,prod,cat,emp}}
function table(headers,rows){return `<div class="report-panel"><table class="ur-table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}" class="report-empty">No data in this period.</td></tr>`}</tbody></table></div>`}
function summaryTab(d){const margin=d.sales?d.gross/d.sales*100:0,top=[...d.prod.entries()].sort((a,b)=>b[1].sales-a[1].sales).slice(0,10);return `<div class="report-cards"><div><span>Net Sales</span><strong>${money(d.sales)}</strong></div><div><span>Transactions</span><strong>${d.tx.length}</strong></div><div><span>Average Ticket</span><strong>${money(d.avg)}</strong></div><div><span>Cash Sales</span><strong>${money(d.pay.cash)}</strong></div><div><span>Card Sales</span><strong>${money(d.pay.card)}</strong></div><div><span>Discounts</span><strong>${money(d.disc)}</strong></div><div><span>Returns</span><strong>${money(d.ret)}</strong></div><div><span>Est. Gross Profit</span><strong>${money(d.gross)}</strong></div><div><span>Est. Margin</span><strong>${margin.toFixed(1)}%</strong></div></div><h3 class="report-title">Top Products</h3>${table(['Product','Qty','Sales','Est. Profit'],top.map(([n,v])=>`<tr><td><strong>${esc(n)}</strong></td><td>${v.qty}</td><td>${money(v.sales)}</td><td>${money(v.sales-v.cost)}</td></tr>`))}`}
function employeeTab(d){return table(['Employee','Transactions','Sales','Avg Ticket'],[...d.emp.entries()].sort((a,b)=>b[1].sales-a[1].sales).map(([n,v])=>`<tr><td><strong>${esc(n)}</strong></td><td>${v.transactions}</td><td>${money(v.sales)}</td><td>${money(v.transactions?v.sales/v.transactions:0)}</td></tr>`))}
function categoryTab(d){return table(['Category','Qty Sold','Sales','Est. COGS','Est. Profit'],[...d.cat.entries()].sort((a,b)=>b[1].sales-a[1].sales).map(([n,v])=>`<tr><td><strong>${esc(n)}</strong></td><td>${v.qty}</td><td>${money(v.sales)}</td><td>${money(v.cost)}</td><td>${money(v.sales-v.cost)}</td></tr>`))}
function productTab(d){return table(['Product','Category','Qty Sold','Sales','Est. COGS','Est. Profit'],[...d.prod.entries()].sort((a,b)=>b[1].sales-a[1].sales).map(([n,v])=>`<tr><td><strong>${esc(n)}</strong></td><td>${esc(v.category)}</td><td>${v.qty}</td><td>${money(v.sales)}</td><td>${money(v.cost)}</td><td>${money(v.sales-v.cost)}</td></tr>`))}
function paymentTab(d){const split=d.tx.filter(t=>new Set((t.payments||[]).map(p=>p.type)).size>1).length;return `<div class="report-cards"><div><span>Cash</span><strong>${money(d.pay.cash)}</strong></div><div><span>Card</span><strong>${money(d.pay.card)}</strong></div><div><span>Split Transactions</span><strong>${split}</strong></div></div>${table(['Transaction','Employee','Payment','Total'],d.tx.map(t=>{const types=[...new Set((t.payments||[]).map(p=>p.type))].join(' + ')||'—';return `<tr><td>${esc(t.transactionNumber||'')}</td><td>${esc(t.employee||'Owner')}</td><td>${esc(types)}</td><td>${money(t.total)}</td></tr>`}))}`}
function discountTab(d){const rows=d.tx.filter(t=>Number(t.discountAmount||0)>0).map(t=>`<tr><td>${esc(t.transactionNumber||'')}</td><td>${esc(t.employee||'Owner')}</td><td>${esc(t.discountLabel||'Discount')}</td><td>${money(t.discountAmount)}</td><td>${money(t.total)}</td></tr>`);return `<div class="report-cards"><div><span>Total Discounts</span><strong>${money(d.disc)}</strong></div><div><span>Discounted Sales</span><strong>${rows.length}</strong></div></div>${table(['Transaction','Employee','Discount','Amount','Final Total'],rows)}`}
function profitTab(d){const margin=d.sales?d.gross/d.sales*100:0;return `<div class="report-cards"><div><span>Sales</span><strong>${money(d.sales)}</strong></div><div><span>Est. COGS</span><strong>${money(d.cogs)}</strong></div><div><span>Est. Gross Profit</span><strong>${money(d.gross)}</strong></div><div><span>Est. Margin</span><strong>${margin.toFixed(1)}%</strong></div></div><div class="ur-role-note">Profit is estimated using the <strong>current product cost</strong> in Inventory. Later, completed transactions will store historical unit cost so margin remains exact even after vendor costs change.</div>${productTab(d)}`}
function returnsTab(d){return `<div class="report-cards"><div><span>Return Total</span><strong>${money(d.ret)}</strong></div><div><span>Return Transactions</span><strong>${d.returns.length}</strong></div></div>${table(['Transaction','Date','Employee','Customer','Amount','Status'],d.returns.map(t=>`<tr><td>${esc(t.transactionNumber||'')}</td><td>${new Date(t.createdAt).toLocaleString()}</td><td>${esc(t.employee||'Owner')}</td><td>${esc(t.customerName||'Walk-in')}</td><td>${money(Math.abs(Number(t.total||0)))}</td><td>${esc(t.status||'Return')}</td></tr>`))}`}
function saveSnapshot(){const d=reportData('all');const snap={updatedAt:new Date().toISOString(),business:'Smoke Signals',netSales:d.sales,transactions:d.tx.length,cashSales:d.pay.cash,cardSales:d.pay.card,discounts:d.disc,returns:d.ret,estimatedCogs:d.cogs,estimatedGrossProfit:d.gross};localStorage.setItem(SNAPSHOT_KEY,JSON.stringify(snap));return snap}
function renderReports(r='today',tab='summary'){if(!can('reports')){toast('You do not have permission to view reports.');return}show();active('reports');const d=reportData(r),tabs=[['summary','Overview'],['employee','By Employee'],['category','By Category'],['product','By Product'],['payment','Payments'],['discount','Discounts'],['profit','Profit / Margin'],['returns','Returns']];const content={summary:summaryTab,employee:employeeTab,category:categoryTab,product:productTab,payment:paymentTab,discount:discountTab,profit:profitTab,returns:returnsTab}[tab](d);$('placeholderView').innerHTML=`<div class="ur-page"><div class="ur-head"><div><h1>Reports</h1><p>Sales, payment, employee, product, category, discount, return and margin reporting.</p></div><select id="urReportRange"><option value="today" ${r==='today'?'selected':''}>Today</option><option value="7" ${r==='7'?'selected':''}>Last 7 Days</option><option value="30" ${r==='30'?'selected':''}>Last 30 Days</option><option value="90" ${r==='90'?'selected':''}>Last 90 Days</option><option value="all" ${r==='all'?'selected':''}>All Time</option></select></div><div class="report-tabs">${tabs.map(([id,l])=>`<button type="button" data-report-tab="${id}" class="${id===tab?'active':''}">${l}</button>`).join('')}</div><div id="reportContent">${content}</div></div>`;$('urReportRange')?.addEventListener('change',e=>renderReports(e.target.value,tab));document.querySelectorAll('[data-report-tab]').forEach(b=>b.addEventListener('click',()=>renderReports(r,b.dataset.reportTab)));saveSnapshot()}
// Correct the employee name on every newly saved transaction before receipt-flow sees it.
const priorSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(this===localStorage&&key===TX_KEY){try{const list=JSON.parse(value||'[]');if(Array.isArray(list)&&list[0]){const u=currentUser();if((list[0].status||'Completed')==='Completed')list[0].employee=u.name;value=JSON.stringify(list)}}catch{}}const result=priorSetItem.call(this,key,value);if(this===localStorage&&key===TX_KEY)setTimeout(saveSnapshot,0);return result};
const st=document.createElement('style');st.textContent=`.ur-page{min-width:0}.ur-head{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:14px}.ur-head h1{margin:0}.ur-head p{margin:4px 0 0;color:var(--muted);font-size:13px}.ur-head select{border:1px solid var(--border);border-radius:10px;background:#fff;padding:10px 12px;font-weight:750}.ur-table-wrap,.report-panel{background:#fff;border:1px solid var(--border);border-radius:12px;overflow:auto}.ur-table{width:100%;border-collapse:collapse}.ur-table th,.ur-table td{padding:11px;border-bottom:1px solid var(--border);font-size:12px;text-align:left}.ur-table th{background:#f1f4f2;font-size:11px;text-transform:uppercase}.ur-active,.ur-inactive,.ur-current{display:inline-block;border-radius:999px;padding:4px 8px;font-weight:850}.ur-active{background:var(--greenSoft);color:var(--green2)}.ur-inactive{background:#f1f1f1;color:#777}.ur-current{margin-left:7px;background:#eef3ff;color:#335}.ur-role-note{background:#fff;border:1px solid var(--border);border-radius:10px;padding:10px 12px;margin-bottom:12px;font-size:12px;color:#555}.ur-permissions{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;border:1px solid var(--border);border-radius:10px;padding:10px}.ur-permissions label{display:flex;align-items:center;gap:7px;font-size:12px}.ur-switch-list{display:grid;gap:8px}.ur-switch-user{display:flex;align-items:center;gap:10px;width:100%;border:1px solid var(--border);background:#fff;border-radius:10px;padding:10px;text-align:left}.ur-switch-user:hover{background:#f6faf6}.ur-switch-user small,.ur-switch-user strong{display:block}.ur-switch-user small{color:var(--muted);margin-top:2px}.ur-avatar{width:36px;height:36px;border-radius:50%;display:grid;place-items:center;background:var(--greenSoft);color:var(--green2);font-weight:900}.ur-error{color:var(--danger);min-height:18px;font-size:12px}.report-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:14px}.report-cards>div{background:#fff;border:1px solid var(--border);border-radius:12px;padding:14px}.report-cards span,.report-cards strong{display:block}.report-cards span{font-size:11px;color:var(--muted);font-weight:800;text-transform:uppercase}.report-cards strong{font-size:24px;margin-top:5px;color:var(--green2)}.report-tabs{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:12px}.report-tabs button{border:1px solid var(--border);background:#fff;border-radius:999px;padding:7px 11px;font-weight:800;font-size:11px}.report-tabs button.active{background:var(--green2);color:#fff;border-color:var(--green2)}.report-title{margin:8px 0}.report-empty{padding:28px!important;text-align:center!important;color:var(--muted)}@media(max-width:900px){.report-cards,.ur-permissions{grid-template-columns:1fr 1fr}.ur-head{align-items:flex-start;flex-direction:column}.ur-head select{width:100%}}@media(max-width:600px){.report-cards,.ur-permissions{grid-template-columns:1fr}}`;document.head.appendChild(st);
window.addEventListener('click',e=>{const nav=e.target.closest?.('.nav-btn[data-view]');if(nav&&!can(nav.dataset.view)){e.preventDefault();e.stopImmediatePropagation();toast('You do not have permission to access that module.');return}const u=e.target.closest?.('.nav-btn[data-view="users"]');if(u){e.preventDefault();e.stopImmediatePropagation();renderUsers();return}const r=e.target.closest?.('.nav-btn[data-view="reports"]');if(r){e.preventDefault();e.stopImmediatePropagation();renderReports();return}if(e.target.closest?.('.user-card')){e.preventDefault();switchUserModal();return}const sw=e.target.closest?.('[data-switch-user]');if(sw){e.preventDefault();trySwitch(sw.dataset.switchUser);return}if(e.target.closest?.('#urAddUser')){e.preventDefault();userForm(null);return}const ed=e.target.closest?.('.ur-edit');if(ed){const row=ed.closest('[data-user-id]'),user=loadUsers().find(x=>String(x.id)===String(row?.dataset.userId));if(user)userForm(user);return}if(e.target.closest?.('[data-ur-close]')){e.preventDefault();close()}},true);
applyPermissions();saveSnapshot();})();